portfolio/main/routes.py
from flask import render_template, request, Blueprint
from portfolio.Calculations import get_general_stock_data, get_graph_by_time, get_stock_price_change

main = Blueprint('main', __name__)

@main.route("/",methods=[ 'POST', 'GET'])
@main.route("/home",methods=[ 'POST', 'GET'])
def home():

    general_indexes = [{'Name': 'S&P  500', 'symbol':'^GSPC'},{'Name': 'Nasdaq100', 'symbol':'^NDX'}]
    all_data = []
    for index in general_indexes:
        symbol = index['symbol']
        stock_data = get_general_stock_data(symbol=symbol)  # S&P 500 index
        if stock_data!= -1:
            stock_data['Name'] = index['Name']
            all_data.append(stock_data)

    time_period = '1d'
    if request.method == 'POST':
        time_period = request.form.get('time-period')
    symbol = '^GSPC'
    graph_data = get_graph_by_time(symbol, time_period=time_period)
    profits =   ((graph_data.get('prices')[-1] - graph_data.get('prices')[0] )
                    ,((graph_data.get('prices')[-1] -graph_data.get('prices')[0])/ graph_data.get('prices')[0] *100) )
    if time_period == '1d':
        profits = get_stock_price_change(symbol)
    return render_template('Home.html' ,all_data=all_data , graph_data = graph_data,profits = profits)

@main.route("/about")
def about():
    return render_template('about.html')

portfolio/stocks/routes.py
from flask import  request, render_template, url_for, redirect, Blueprint
from portfolio.models import  Current_portfolio
from flask_login import  current_user, login_required
from portfolio.Calculations import (get_portfolio_data,
                                    updatePortfolio , get_general_stock_data,get_graph_by_time, get_stock_price_change)
import datetime as dt

stocks = Blueprint('stocks', __name__)


@login_required
@stocks.route("/My_portfolio")
def My_portfolio():
    myPortfolio = Current_portfolio.query.filter_by(portfolio_owner=current_user).all()
    updatePortfolio(myPortfolio)
    portfolio_data = get_portfolio_data(myPortfolio)
    portfolio_allocation = [(stock.stock_name, stock.sum_over_all / portfolio_data['portfolio_value'] * 100) for stock in myPortfolio]
    return render_template('portfolio.html', title='My Portfolio', myPortfolio=myPortfolio, portfolio_data=portfolio_data,portfolio_allocation=portfolio_allocation)


@stocks.route("/stock/", methods=['POST','GET'])
@stocks.route("/stock/<string:stock_symbol>", methods=[ 'POST', 'GET'])
def stock(stock_symbol=None):

    search = request.args.get('search', '')
    if search == '':
        search = stock_symbol
    time_period = '1d'
    if request.method == 'POST':
        time_period = request.form.get('time-period')
        print(f'datw tie: {time_period}')
    stock_data = get_general_stock_data(search)
    print(stock_data)
    graph_data = get_graph_by_time(search, time_period=time_period)
    profits =   ((graph_data.get('prices')[-1] - graph_data.get('prices')[0] )
                    ,((graph_data.get('prices')[-1] -graph_data.get('prices')[0])/ graph_data.get('prices')[0] *100) )
    if time_period == '1d':
        profits = get_stock_price_change(search)
    print(graph_data)
    return render_template('stock.html', stock_symbol=search,stock_data=stock_data, graph_data = graph_data, profits = profits)

portfolio/transactions/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from portfolio import db
from portfolio.models import Transaction, Current_portfolio,User
from portfolio.Calculations import get_price_by_date
from portfolio.transactions.forms import TransactionForm
import datetime as dt

transactions = Blueprint('transactions', __name__)


@login_required
@transactions.route("/transaction_history")
def transaction_history():
    page = request.args.get('page',1, type=int)
    myTransactions = Transaction.query.filter_by(Transactionsmanager=current_user).order_by(Transaction.transaction_date.desc()).paginate(page=page,per_page = 15)
    myPortfolio = Current_portfolio.query.filter_by(portfolio_owner=current_user).all()
    portfolio_value = round(sum(item.sum_over_all for item in myPortfolio),2)
    return render_template('transaction_history.html', transactions=myTransactions, portfolio_value=portfolio_value)


@transactions.route("/transaction/new", methods = ['GET','POST'])
@login_required
def new_transaction():
    form = TransactionForm()
    if  form.validate_on_submit() and form.validate_quantity(quantity=form.quantity) :
        # Get the stock price on the transaction date
        priceStock = round(get_price_by_date(form.name.data, form.transaction_date.data), 2)
        form.fill_MissingValues(priceStock)
        # Check the transaction type
        if form.submitBuy.data:
            transaction_type = 'Buy'
        elif form.submitSell.data:
            transaction_type = 'Sell'
        else:
            flash("Invalid transaction type", 'danger')
            return redirect(url_for('transactions.new_transaction'))

        # Calculate price per unit and create a transaction record
        pricePerUnit = round(form.sum_over_all.data / form.quantity.data, 2)
        transaction = Transaction(
            stock_name=form.name.data,
            quantity=form.quantity.data,
            price_per_unit=pricePerUnit,
            sum_over_all=form.sum_over_all.data,
            transaction_date=form.transaction_date.data,
            transaction_type=transaction_type,
            Transactionsmanager=current_user
        )

        db.session.add(transaction)
        db.session.commit()

        user_portfolio = Current_portfolio.query.filter_by(portfolio_owner=current_user, stock_name=form.name.data).first()
        free_cash  = current_user.free_money
        if free_cash < form.sum_over_all.data and transaction_type == 'Buy':
            flash(f'You dont have this amount of money, you only have {free_cash}', 'danger')
            return redirect(url_for('transactions.new_transaction'))
        if not user_portfolio:
            user_portfolio = Current_portfolio(
                stock_name=form.name.data,
                quantity=form.quantity.data,
                buy_price=pricePerUnit,
                curr_price=pricePerUnit,
                sum_over_all=form.sum_over_all.data,
                portfolio_owner=current_user
            )

            current_user.free_money -= form.sum_over_all.data
            db.session.add(user_portfolio)
        elif transaction_type == 'Buy':
            # Use more money that you have
            user_portfolio.quantity += form.quantity.data
            user_portfolio.sum_over_all += form.sum_over_all.data
            current_user.free_money -= form.sum_over_all.data

            if user_portfolio.quantity == 0:
                user_portfolio.buy_price = 0
            else:
                # The new buy price
                user_portfolio.buy_price = round((user_portfolio.buy_price * (user_portfolio.quantity - form.quantity.data) + form.sum_over_all.data) /
                    user_portfolio.quantity, 2)
        else:
            user_portfolio.quantity -= form.quantity.data
            if user_portfolio.quantity <= 0:
                db.session.delete(user_portfolio)
            user_portfolio.curr_price = user_portfolio.sum_over_all - form.sum_over_all.data
            user_portfolio.sum_over_all -= form.sum_over_all.data
            current_user.free_money += form.sum_over_all.data

        db.session.commit()
        flash("Your Transaction has been updated", 'success')
        return redirect(url_for('stocks.My_portfolio'))
    elif request.method == 'GET':
        form.transaction_date.data = dt.datetime.now().date()

    return render_template('new_transaction.html', title='New Transaction', form=form)

portfolio/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from portfolio import db, bcrypt
from portfolio.models import User
from portfolio.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from portfolio.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, free_money = 15000)
        db.session.add(user)
        db.session.commit()

        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods = ['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Log in not please check your password or email', category='danger')
    return render_template('login.html', form = form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods = ['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been update', 'succes')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title = 'Account', form = form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has benn sent with instruction to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expires token', 'warning')
        return redirect(url_for('users.reset_reques'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()

        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route("/balance")
@login_required
def balance():
    account_balance =  current_user.free_money
    return render_template('balance.html',account_balance = account_balance)

portfolio/templates/Home.html
{% extends "layout.html" %}
{% block content %}
    <h2>Index Stock Data</h2>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Open Price</th>
            <th>Current Price</th>
            <th>Profit Today</th>
        </tr>
        <tr>
            {% for stock_data in all_data %}
                <td>
                    {{ stock_data.Name }}</td>
                <td>{{ stock_data.open_price | round(2) }}</td>
                <td>{{ stock_data.curr_price | round(2) }}</td>
                <td style="color: {% if stock_data.profitValue > 0 %}#008000{% else %}#ff0000{% endif %};">
                    {{ stock_data.profitValue | round(2)}}
                    ({{ stock_data.profitPercent | round(2)}}%)</td>

                </tr>
            {% endfor %}
        </tr>
    </table>
    <div>
        <label for="time-period">Select Time Period:</label>
        <form method="post">
            <select name="time-period">
                {% set time_periods = [('1d', '1 Day'), ('5d', '5 Days'),('1m', '1 Month'), ('6m', '6 Months'), ('ytd', 'Year-to-Date'), ('1y', '1 Year'), ('5y', '5 Years')] %}
                {% for value, label in time_periods %}
                    <option value="{{ value }}" {% if request.form.get('time-period') == value %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
            <button type="submit">Submit</button>
        </form>

    </div>
     <div >
         <h4 >Profit:
                <small  style="color: {% if profits[0] > 0 %}#008000{% else %}#ff0000{% endif %};">
                    {{profits[0]|round(2)}} $
                    ({{profits[1] |round(2)}}%)</small>
         </h4>
                 </div>
        <div id="stock-graph" >
    </div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>
    function createStockGraph() {
        // Sample data (replace with actual data)
        const graph_data = {{ graph_data | tojson | safe }};
        const profit  = {{profits[0]}}
        const lineColor = profit >= 0 ? 'green' : 'red';
        const markerColor = profit >= 0 ? 'green' : 'red';
        // Define the trace for the graph
        const trace = {
            x: graph_data.dates,
            y: graph_data.prices,
            type: 'scatter',
            mode: 'lines',
            line: {
            color: lineColor,
        },
        };
        // Define the layout options
        const layout = {
            title: 'Stock Price Graph for a year of {{all_data[0].Name}}',
            xaxis: {
                title: 'Date',
            },
            yaxis: {
                title: 'Price',
            },
        };

        // Create the graph
        const data = [trace];
        Plotly.newPlot('stock-graph', data, layout);
    }

    // Call the function to create the graph when the page loads
    window.onload = createStockGraph();
</script>

{% endblock content %}

portfolio/templates/Layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-xHjDBv9jTzwa/5p5V0w8J5zr7Z9DE4OHDP8w5hrPZfy5CpIW1jFduK3vH4r0Jluuy" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <title>Flask Portfolio</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Portfolio</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('stocks.My_portfolio') }}">My Portfolio</a>
                    <a class="nav-item nav-link" href="{{ url_for('transactions.transaction_history') }}">Transaction History</a>
                    <a class="nav-item nav-link" href="{{ url_for('transactions.new_transaction') }}">New Transaction</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.balance') }}">Balance</a>

                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <div class="search-container">
                <form action="{{ url_for('stocks.stock', stock_symbol=stock_symbol) }}" method="get">
                    <input type="text" id="search" placeholder="Search symbol" name="search" />
                    <button type="submit">Search</button>
                </form>


              </div>
            {%     if current_user.is_authenticated  %}
                <a class="nav-item nav-link" href={{url_for('users.account')}}>Account</a>
                <a class="nav-item nav-link" href={{url_for('users.logout')}}>Logout</a>
            {% else %}
              <a class="nav-item nav-link" href={{url_for('users.login')}}>Login</a>
              <a class="nav-item nav-link" href={{url_for('users.register')}}>Register</a>
            {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories =true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{category}}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <!--
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>-->
      </div>
    </main>


    <!-- Optional JavaScript -->
    <script type="text/javascript">


            function sendToPage(){
                var input = document.getElementById("search").value;
                 location.href = url_for('stock', stock_symbol=input) "
                    }
    </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
    <p>Welcome to our financial portfolio management application!</p>

    <h2>Features</h2>
    <ul>
        <li>Track your investments and portfolio performance.</li>
        <li>View real-time stock prices and historical data.</li>
        <li>Manage your cash balance and transaction history.</li>
        <!-- Add more features as needed -->
    </ul>

    <h2>How It Works</h2>
        <p>Our application provides a user-friendly interface to help you manage your financial portfolio efficiently. When you sign up, you'll start with a demo trading balance of $15,000. This allows you to explore the features of our platform without using real money.</p>

        <p>Simply log in to your account, where you'll have the freedom to:</p>
        <ul>
            <li>Explore real-time stock prices and historical data.</li>
            <li>Track your investments and monitor portfolio performance.</li>
            <li>Execute demo trades to simulate buying and selling stocks.</li>
            <li>View detailed transaction history to analyze your trading decisions.</li>
        </ul>

        <p>Our goal is to provide you with a risk-free environment where you can practice and refine your investment strategies. Feel free to experiment with different stocks, observe market trends, and make informed decisions based on the wealth of real-time market data available.</p>

<h2>Navigation Bar and Different Pages</h2>
    <p>Our application is designed with various pages to cater to different aspects of your financial journey. Here's a brief overview:</p>

    <ul>
        <li><strong>Home Page:</strong> The home page offers a comprehensive overview of the two primary stock market indexes: S&P 500 and Nasdaq 100. Gain insights into the performance and trends of these key indices to make informed investment decisions.</li>
        <li><strong>Portfolio Page:</strong> Dive into the details of your current investment portfolio. View information on individual stocks, their quantities, and current values.</li>
        <li><strong>New Transaction Page:</strong> Practice buying and selling stocks in a simulated environment. Use the user-friendly interface to execute trades without real financial risk.</li>
        <li><strong>Transaction History Page:</strong> Review a detailed history of your past transactions. Track every buy and sell action to analyze your trading decisions and performance over time.</li>
        <li><strong>Stock Search Bar:</strong> Utilize the search bar to explore and discover stocks. Get real-time information on stock prices, trends, and company details. The search bar empowers you to make well-informed investment choices.</li>
        <li><strong>Balance Page:</strong> Monitor your available cash balance. Gain insights into the amount of free money in your account.</li>
        <li><strong>About Page:</strong> You're currently on the about page! Learn more about the application, its purpose, and how each page contributes to your financial management journey.</li>
    </ul>

    <p>Explore these pages to make the most of our financial portfolio management app.</p>
{% endblock content %}

portfolio/templates/balance.html
{% extends "layout.html" %}

{% block content %}
    <h1>Cash Page</h1>
    <h3>Your account balance: ${{ account_balance|round(2) }}</h3>
    <p>Explore your financial standing on the Balance Page.
        This page provides a snapshot of your current account balance, giving you a quick overview of your available funds.</p>

{% endblock content %}

portfolio/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

portfolio/templates/portfolio.html
{% extends "layout.html" %}
{% block content %}
    <h2 style="display: inline;">My Portfolio - Portfolio Value:<br>
        ${{ portfolio_data.portfolio_value | round(2) }}</h2>
    <p style="color: {% if portfolio_data.portfolio_profitValue >= 0 %}#008000{% else %}#ff0000{% endif %}; display: inline;">
        ${{ portfolio_data.portfolio_profitValue | round(2) }} ({{ portfolio_data.portfolio_profitPercent | round(2) }}%)
    </p>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Stock Name</th>
                <th>Total Quantity</th>
                <th>Price per Unit buying</th>
                <th>Price per Unit Now</th>
                <th>Total Sum Over All</th>
                <th>Profit</th>
                <th>Change Today</th>
                <th>Action</th>  <!-- Added a column for actions -->
            </tr>
        </thead>
        <tbody>
            {% for stock in myPortfolio %}
                <tr>
                    <td><a class="nav-item nav-link" href = "{{ url_for('stocks.stock', stock_symbol=stock.stock_name) }}">
                        {{ stock.stock_name }}</a></td>
                    <td>{{ stock.quantity }}</td>
                    <td>${{ stock.buy_price | round(2) }}</td>
                    <td>${{ stock.curr_price | round(2) }}</td>
                    <td>${{ stock.sum_over_all | round(2) }}</td>
                    <td style="color: {% if stock.profitValue >= 0 %}#008000{% else %}#ff0000{% endif %};">
                        ${{ stock.profitValue | round(2) }} ({{ stock.profitPercent | round(2) }}%)
                    </td>
                    <td style="color: {% if stock.change_value_today >= 0 %}#008000{% else %}#ff0000{% endif %};">
                        ${{ stock.change_value_today | round(2) }} ({{ stock.change_percent_today | round(2) }}%)
                    </td>
                    <td>
                        <form method="POST" action="{{ url_for('transactions.new_transaction') }}">
                            <input type="hidden" name="stock_name" value="{{ stock.stock_name }}">
                            <button type="submit" class="btn btn-danger">Sell</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", {packages: ["corechart"]});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Stock Name');
            data.addColumn('number', 'Allocation');

            data.addRows([
                {% for key, value in portfolio_allocation %}
                ["{{ key }}", {{ value }}],
                {% endfor %}
            ]);

            var options = {
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }
    </script>
    <h3>Portfolio Allocation</h3>

    <div id="piechart" class="content-section" style="width: 730px; height:500px;">
    </div>

{% endblock content %}

portfolio/templates/transaction_history.html
{% extends "layout.html" %}
{% block content %}
    <head>
        <h1>Transaction history</h1>
        <h3 "display: inline"> Portfolio Value: {{ portfolio_value }}$</h3>
    </head>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Stock Name</th>
                <th>Quantity</th>
                <th>Price per Unit</th>
                <th>Sum Over All</th>
                <th>Transaction Type</th>
                <th>Transaction Date</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions.items %}
                <tr>
                    <td>
                        <a class="nav-item nav-link" href = "{{ url_for('stocks.stock', stock_symbol=transaction.stock_name ) }}">
                        {{ transaction.stock_name }}</a></td>
                    <td>{{ transaction.quantity  | round(2)}}</td>
                    <td>${{ transaction.price_per_unit  | round(2)}}</td>
                    <td>${{ transaction.sum_over_all  | round(2)}}</td>
                    <td>{{ transaction.transaction_type }}</td>
                    <td>{{ transaction.transaction_date.strftime('%d-%m-%Y') }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% for page_num in transactions.iter_pages(left_edge =1, right_edge =1, left_current =1, right_current =2) %}
        {% if page_num %}
            {% if transactions.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('transactions.transaction_history', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outlint-info mb-4" href="{{ url_for('transactions.transaction_history', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock content %}